AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  AWS CloudFormation Template "production": This CloudFormation template creates 2 S3 bucket for WAR + static content.
Parameters:
  BucketName:
    Description: The name of the S3 Bucket to create
    Type: String
    Default: company-news-static-assets-production
  EnvironmentName:
    Description: An environment name that will be added to resource descriptions
    Type: String
    Default: production
    AllowedValues:
      - training
      - production
  EnvironmentLocation:
    Description: Name of the AWS region that is being used
    Type: String
    Default: ap-southeast-2
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
    DeletionPolicy: Retain
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join 
              - ''
              - - 'arn:aws:s3:::'
                - !Ref S3Bucket
                - /*
      Bucket: !Ref S3Bucket
Outputs:
  WebsiteURL:
    Value: !GetAtt 
      - S3Bucket
      - WebsiteURL
    Description: URL for website hosted on S3
  S3BucketSecureURL:
    Value: !Join 
      - ''
      - - 'https://'
        - !GetAtt 
          - S3Bucket
          - DomainName
    Description: Name of S3 bucket to hold website content